### ISSUE TITLE
三笔重合==》本级别中枢 

### ISSUE THREAD

**Issue by natalienie** [jiangzhe/tanglism#14]
优先级： 强

目的： 在当前级别找到同级别中枢。

步骤：

1. 找中枢。按照定义，三笔重合即可构成中枢。 上升趋势里中枢由，下上下，三笔即可构成，下降趋势里中枢由，上，下，上三笔构成。

2. 中枢的延伸。 中枢最少三笔，但4-8笔也都可以。如果是静态的分析，那么没有问题按照这个3-9的定义来。

3. 如果是动态的，有了三笔构成中枢之后，我们就可以动态操作，进行前后两段macd 力度的比较，如果后一段力度小于前一段，就可以肯定有回拉（反向笔），回拉有两种可能，一种是回到中枢区间，那么这一段就被之前中枢吸纳了，也就是算是原来中枢里的一部分。 另一种可能是没有拉回原来中枢，反弹的这笔只和之前构成中枢三笔中的最后一笔有重合，这样这两笔又构成了一个新的中枢（结合律）。下一个力度的比较就按照新的中枢来， 把之前中枢的第一二笔归类到前面走势去。 

举例：
 1 + （2+ 3 +4）是一个走势类型， 奇数是向上笔，偶数是向下笔，括号里是中枢，当走出5， 6的时候，（4，5，6） 如果有重合又可以构成新的中枢了， 那么就应该这样来分解走势 1+2+3 +（4+5+6）。

**Comment by jiangzhe** [comment]
缠论中是以次级别走势来定义中枢的，所以用笔查找中枢作为一个可选功能。
另外，上升和下降趋势如何确定？直接使用线段作为当前级别的走势么？

**Comment by natalienie** [comment]
要是能严格按照禅师定义从次级别推倒上来确认中枢，我非常期待，因为人干这事儿容易晕不直观。线段可以作为当前级别走势。

**Comment by jiangzhe** [comment]
缠论中并不推荐使用笔中枢。http://blog.sina.com.cn/s/blog_486e105c01000cqy.html
单考虑到实用性和易实现性，可以在界面提供笔中枢功能。
中枢判断逻辑依据。http://blog.sina.com.cn/s/blog_486e105c010007t8.html
“缠中说禅走势中枢定理一”：在趋势中，连接两个同级别“缠中说禅走势中枢”的必然是次级别以下级别的走势类型。
“缠中说禅走势中枢定理二”：在盘整中，无论是离开还是返回“缠中说禅走势中枢”的走势类型必然是次级别以下的。
“缠中说禅走势中枢”定理三：某级别“缠中说禅走势中枢”的破坏，当且仅当一个次级别走势离开该“缠中说禅走势中枢”后，其后的次级别回抽走势不重新回到该“缠中说禅走势中枢”内。
